//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertGeneratorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadsData
    {
        public long Id { get; set; }
        public int SubscriberId { get; set; }
        public int AlertAttributeId { get; set; }
        public System.DateTime FromTime { get; set; }
        public System.DateTime ToTime { get; set; }
        public long Value { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public int RowVersion { get; set; }
    
        public virtual AlertAttribute AlertAttribute { get; set; }
    }
}
